// This file was generated by Prisma, and assumes you run Prisma commands using `bun --bun run prisma [command]`.
import { defineConfig, env } from "prisma/config";
import "dotenv/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // CLI (migrate/studio) needs the session pooler — transaction pooler hangs migrate dev
    url: env("DIRECT_URL"),
    shadowDatabaseUrl: env("SHADOW_DATABASE_URL"), // local postgres; Supabase forbids CREATEDB
  },
});
